
{REDUND_ERROR} FUNCTION_BLOCK ksStepHistory (*speichert Schritthistorie*) (*$GROUP=User,$CAT=User,$GROUPICON=User.png,$CATICON=User.png*)
	VAR_INPUT
		in_Step : {REDUND_UNREPLICABLE} KsStepData_type;
		in_ET : {REDUND_UNREPLICABLE} TIME;
	END_VAR
	VAR
		aData : {REDUND_UNREPLICABLE} ARRAY[0..MAX_IDX_STEP_HISTORY_ENTRIES] OF ksStepHistoryEntry;
		i : {REDUND_UNREPLICABLE} USINT;
		Last : USINT;
	END_VAR
END_FUNCTION_BLOCK
